version = 3.10.3
runner.dialect = scala3
maxColumn = 120
newlines.source = unfold
rewrite.rules = [Imports, AvoidInfix, RedundantParens, RemoveSemicolons]
rewrite.imports.sort = ascii
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces.enabled = true
rewrite.scala3.removeOptionalBraces.fewerBracesMinSpan = 1
rewrite.scala3.removeOptionalBraces.fewerBracesMaxSpan = 2147483647
rewrite.scala3.endMarker.insertMinSpan = 10
rewrite.scala3.endMarker.removeMaxSpan = 9
