[package]
name = "camel"
version = "1.0.2"
edition = "2021"

[dependencies]
bitflags = "2.3.3"
primitive_enum = "1.1.1"
derive_more = "0.99.17"
rand = "0.8.5"
once_cell = "1.18.0"
smallvec = "1.11.0"
ahash = "0.8.3"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
