[package]
name = "camel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
once_cell = "1.17.0"
bitflags = "1.3.2"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "movegen"
harness = false

[[bench]]
name = "search"
harness = false
