[package]
name = "camel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.1"
num_enum = "0.6.1"
derive_more = "0.99.17"
tinyrand = "0.5.0"
tinyrand-std = "0.5.0"
array-init = "2.1.0"