[package]
name = "camel"
version = "1.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.0"
primitive_enum = "1.1.1"
derive_more = "0.99.17"
rand = "0.8.5"
once_cell = "1.18.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "movegen"
harness = false

[[bench]]
name = "eval"
harness = false
