[package]
name = "camel"
version = "2.0.0-alpha"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
clap = { version = "4.5.40", features = ["derive"] }
ctor = "0.5.0"
derive_more = { version = "2.1.0", features = ["full"] }
primitive_enum = "1.2.0"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"

[dev-dependencies]
rstest = "0.26.1"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
panic = "abort"
strip = "debuginfo"
