[package]
name = "camel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
once_cell = "1.17.0"
bitflags = "1.3.2"
smallvec = "1.10.0"
num_cpus = "1.15.0"