# see https://docs.codecov.io/docs/codecov-yaml
# Validation check:
# $ curl --data-binary @codecov.yml https://codecov.io/validate

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 0  # 2 = xx.xx%, 0 = xx%
  round: up # how coverage is rounded: down/up/nearest
  range: 60...100 # custom range of coverage colors from red -> yellow -> green
  status:
    project:
      default:
        informational: true
        target: 70% # specify the target coverage for each commit status
        threshold: 10% # allow this decrease on project
        if_ci_failed: error
    patch:
      default:
        informational: true
        threshold: 20% # allow this decrease on patch
    changes: false

github_checks:
    annotations: true

comment:
  layout: header, diff
  require_changes: false
  behavior: default