name: ci

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Format Rust
        run: cargo fmt --check

      - name: Format Shell
        run: |
          sudo apt-get install shfmt
          shfmt -i 4 -d .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint Rust
        run: cargo clippy --verbose -- -D warnings

      - name: Install cargo-sort
        uses: taiki-e/install-action@cargo-sort

      - name: Lint Cargo.toml
        run: cargo sort --check

      - name: Lint Shell
        uses: ludeeus/action-shellcheck@2.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Test with coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: codecov.json
          fail_ci_if_error: true
