name: gauntlet

on:
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up script permissions
        run: chmod +x ./gauntlet.sh

      - name: Set up local master branch
        run: git fetch origin master:master

      - name: Run script and collect results
        env:
          CURRENT_BRANCH: ${{ github.head_ref }}
        run: |
          ./gauntlet.sh || echo "GAUNTLET_FAILED=1" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(cat fast-chess/message.txt)" >> $GITHUB_ENV

      - uses: phulsechinmay/rewritable-pr-comment@v0.2.1
        with:
          message: ${{ env.COMMIT_MESSAGE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if gauntlet failed
        run: |
          if [ -n "$GAUNTLET_FAILED" ]; then
            exit 1
          fi
