name: gauntlet

on:
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          chmod +x ./gauntlet.sh
          ./gauntlet.sh
          echo "COMMIT_MESSAGE=$(cat fast-chess/message.txt)" >> $GITHUB_ENV

      - uses: phulsechinmay/rewritable-pr-comment@v0.2.1
        with:
          message: ${{env.COMMIT_MESSAGE}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
